In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [98]:
df=pd.read_excel("restaurants__data.xlsx")
df

,Name,Rating,Price Range,Location,Delivery Options
0,Tipsy Turk - Rooftop & Bar,4.4,"Restaurant2nd Floor, Buty Building, Tipsy Turk...",Kerbside pickup,No-contact delivery
1,Hitchki Nagpur,4.4,₹₹₹,"North IndianPark Avenue, Plot no. 2/1 & 11/2 1...",Drive-throughNo-contact delivery
2,Club NH Restaurant - Best Family Restaurant in...,74.2,₹200–400,"Family-friendly124/3 P.H NO. 37 mouza, Hudkesh...",NaN
3,Farmhouse Kitchen Restaurant,4.6,IndianNear Ganesh Lawn East Shankar Nagar Ramd...,NaN,NaN
4,Ramaji's Food Plaza,4.5,₹200–400,"Vegetarian07, Hudkeshwar Rd, opposite padole S...",Kerbside pickupNo-contact delivery
...,...,...,...,...,...
497,Not Just Tamasha,4.0,"₹2,000+","LoungeUnit no 1A & 1B, Victoria House, Pandura...",TakeawayNo-contact delivery
498,Wink,4.3,₹₹₹₹,"BarPresident, Mumbai - IHCL SeleQtions 90, 90C...",NaN
499,Restaurants,4.4,"RestaurantShop no. 971, near lotus petrol pump...",Takeaway,No-contact delivery
500,Mumbai Restaurant,3.8,Meal delivery,NaN,NaN
501,Hotel Jyoti,3.4,"SeafoodShop No. 1, opposite ItiCloses soon ⋅ 1...",Takeaway,NaN

In [99]:
df.isnull().sum()

Name                  0
Rating               13
Price Range           0
Location             59
Delivery Options    226
dtype: int64

In [114]:
df["Delivery Options"]=df["Delivery Options"].fillna("No-contact delivery")
df

,Name,Rating,Price Range,Location,Delivery Options
0,Tipsy Turk - Rooftop & Bar,4.4,"Restaurant2nd Floor, Buty Building, Tipsy Turk...",Kerbside pickup,No-contact delivery
1,Hitchki Nagpur,4.4,₹₹₹,"North IndianPark Avenue, Plot no. 2/1 & 11/2 1...",Drive-throughNo-contact delivery
2,Club NH Restaurant - Best Family Restaurant in...,74.2,₹200–400,"Family-friendly124/3 P.H NO. 37 mouza, Hudkesh...",No-contact delivery
3,Farmhouse Kitchen Restaurant,4.6,IndianNear Ganesh Lawn East Shankar Nagar Ramd...,NaN,No-contact delivery
4,Ramaji's Food Plaza,4.5,₹200–400,"Vegetarian07, Hudkeshwar Rd, opposite padole S...",Kerbside pickupNo-contact delivery
...,...,...,...,...,...
497,Not Just Tamasha,4.0,"₹2,000+","LoungeUnit no 1A & 1B, Victoria House, Pandura...",TakeawayNo-contact delivery
498,Wink,4.3,₹₹₹₹,"BarPresident, Mumbai - IHCL SeleQtions 90, 90C...",No-contact delivery
499,Restaurants,4.4,"RestaurantShop no. 971, near lotus petrol pump...",Takeaway,No-contact delivery
500,Mumbai Restaurant,3.8,Meal delivery,NaN,No-contact delivery
501,Hotel Jyoti,3.4,"SeafoodShop No. 1, opposite ItiCloses soon ⋅ 1...",Takeaway,No-contact delivery

In [115]:
data=df.dropna()

In [117]:
without_na.isnull().sum()

Name                0
Rating              0
Price Range         0
Adreess             0
Delivery Options    0
dtype: int64

In [118]:
data

,Name,Rating,Price Range,Location,Delivery Options
0,Tipsy Turk - Rooftop & Bar,4.4,"Restaurant2nd Floor, Buty Building, Tipsy Turk...",Kerbside pickup,No-contact delivery
1,Hitchki Nagpur,4.4,₹₹₹,"North IndianPark Avenue, Plot no. 2/1 & 11/2 1...",Drive-throughNo-contact delivery
2,Club NH Restaurant - Best Family Restaurant in...,74.2,₹200–400,"Family-friendly124/3 P.H NO. 37 mouza, Hudkesh...",No-contact delivery
4,Ramaji's Food Plaza,4.5,₹200–400,"Vegetarian07, Hudkeshwar Rd, opposite padole S...",Kerbside pickupNo-contact delivery
5,TILT Kitchen & Bar,4.6,"North IndianPlot 7A, Besa Rd, near Central Ban...",Drive-through,Delivery
...,...,...,...,...,...
495,Hotel Jyoti,3.4,"SeafoodShop No. 1, opposite ItiCloses soon ⋅ 1...",Takeaway,No-contact delivery
497,Not Just Tamasha,4.0,"₹2,000+","LoungeUnit no 1A & 1B, Victoria House, Pandura...",TakeawayNo-contact delivery
498,Wink,4.3,₹₹₹₹,"BarPresident, Mumbai - IHCL SeleQtions 90, 90C...",No-contact delivery
499,Restaurants,4.4,"RestaurantShop no. 971, near lotus petrol pump...",Takeaway,No-contact delivery
501,Hotel Jyoti,3.4,"SeafoodShop No. 1, opposite ItiCloses soon ⋅ 1...",Takeaway,No-contact delivery

In [119]:
without_duplicates=data.drop_duplicates()
without_duplicates

,Name,Rating,Price Range,Location,Delivery Options
0,Tipsy Turk - Rooftop & Bar,4.4,"Restaurant2nd Floor, Buty Building, Tipsy Turk...",Kerbside pickup,No-contact delivery
1,Hitchki Nagpur,4.4,₹₹₹,"North IndianPark Avenue, Plot no. 2/1 & 11/2 1...",Drive-throughNo-contact delivery
2,Club NH Restaurant - Best Family Restaurant in...,74.2,₹200–400,"Family-friendly124/3 P.H NO. 37 mouza, Hudkesh...",No-contact delivery
4,Ramaji's Food Plaza,4.5,₹200–400,"Vegetarian07, Hudkeshwar Rd, opposite padole S...",Kerbside pickupNo-contact delivery
5,TILT Kitchen & Bar,4.6,"North IndianPlot 7A, Besa Rd, near Central Ban...",Drive-through,Delivery
...,...,...,...,...,...
479,New Maharashtra Restaurant,4.1,Indian67/A ground floor plot no 67 Esjay house...,Takeaway,No-contact delivery
491,Not Just Tamasha,4.0,"₹2,000+","LoungeUnit no 1A & 1B, Victoria House, Pandura...",TakeawayNo-contact delivery
492,Wink,4.3,₹₹₹₹,"BarPresident, Mumbai - IHCL SeleQtions 90, 90C...",No-contact delivery
493,Restaurants,4.4,"RestaurantShop no. 971, near lotus petrol pump...",Takeaway,No-contact delivery
495,Hotel Jyoti,3.4,"SeafoodShop No. 1, opposite ItiCloses soon ⋅ 1...",Takeaway,No-contact delivery

In [122]:
without_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
Index: 240 entries, 0 to 495
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              240 non-null    object
 1   Rating            240 non-null    float64
 2   Price Range       240 non-null    object
 3   Location          240 non-null    object
 4   Delivery Options  240 non-null    object
dtypes: float64(1), object(4)
memory usage: 11.2+ KB

In [123]:
def has_one_digit_before_and_after(value):
    if isinstance(value, float):  # Ensure the value is a float
        parts = str(value).split(".")  # Split into integer and decimal parts
        return len(parts[0]) == 1 and len(parts[1]) == 1  # Check lengths
    return False

# Filter rows where 'rating' has one digit before and one digit after the decimal
data_filtered = without_duplicates[without_duplicates['Rating'].apply(has_one_digit_before_and_after)]

In [124]:
data_filtered

,Name,Rating,Price Range,Location,Delivery Options
0,Tipsy Turk - Rooftop & Bar,4.4,"Restaurant2nd Floor, Buty Building, Tipsy Turk...",Kerbside pickup,No-contact delivery
1,Hitchki Nagpur,4.4,₹₹₹,"North IndianPark Avenue, Plot no. 2/1 & 11/2 1...",Drive-throughNo-contact delivery
4,Ramaji's Food Plaza,4.5,₹200–400,"Vegetarian07, Hudkeshwar Rd, opposite padole S...",Kerbside pickupNo-contact delivery
5,TILT Kitchen & Bar,4.6,"North IndianPlot 7A, Besa Rd, near Central Ban...",Drive-through,Delivery
6,High Steaks Nagpur,4.5,₹₹₹,"Lounge7th Floor, Hotel Centre Point, 24, Centr...",No-contact delivery
...,...,...,...,...,...
479,New Maharashtra Restaurant,4.1,Indian67/A ground floor plot no 67 Esjay house...,Takeaway,No-contact delivery
491,Not Just Tamasha,4.0,"₹2,000+","LoungeUnit no 1A & 1B, Victoria House, Pandura...",TakeawayNo-contact delivery
492,Wink,4.3,₹₹₹₹,"BarPresident, Mumbai - IHCL SeleQtions 90, 90C...",No-contact delivery
493,Restaurants,4.4,"RestaurantShop no. 971, near lotus petrol pump...",Takeaway,No-contact delivery
495,Hotel Jyoti,3.4,"SeafoodShop No. 1, opposite ItiCloses soon ⋅ 1...",Takeaway,No-contact delivery

In [125]:
data_filtered = data_filtered[~data_filtered['Price Range'].str.contains("₹.*₹", na=False)]

In [127]:
data_filtered

,Name,Rating,Price Range,Location,Delivery Options
0,Tipsy Turk - Rooftop & Bar,4.4,"Restaurant2nd Floor, Buty Building, Tipsy Turk...",Kerbside pickup,No-contact delivery
4,Ramaji's Food Plaza,4.5,₹200–400,"Vegetarian07, Hudkeshwar Rd, opposite padole S...",Kerbside pickupNo-contact delivery
5,TILT Kitchen & Bar,4.6,"North IndianPlot 7A, Besa Rd, near Central Ban...",Drive-through,Delivery
7,Habits Restaurant,4.1,₹400–600,"VegetarianA.B.Hospitality, Shree Ambe Apartmen...",Drive-throughNo-contact delivery
9,Majestic Masala,4.3,"North Indian37, Central Bazar RoadDine-in",Takeaway,No-contact delivery
...,...,...,...,...,...
478,Taj Traders Chicken & Egg Wholesaler and Supplier,5.0,"Chicken shopUnwala compound, Plot no 81, CST R...",No-contact delivery,No-contact delivery
479,New Maharashtra Restaurant,4.1,Indian67/A ground floor plot no 67 Esjay house...,Takeaway,No-contact delivery
491,Not Just Tamasha,4.0,"₹2,000+","LoungeUnit no 1A & 1B, Victoria House, Pandura...",TakeawayNo-contact delivery
493,Restaurants,4.4,"RestaurantShop no. 971, near lotus petrol pump...",Takeaway,No-contact delivery
495,Hotel Jyoti,3.4,"SeafoodShop No. 1, opposite ItiCloses soon ⋅ 1...",Takeaway,No-contact delivery

In [131]:



# Display initial data summary
print("Initial data shape:", data_filtered.shape)

# Filter rows where the 'Price Range' column contains the ₹ symbol
if 'Price Range' in data_filtered.columns:
    data_cleaned = data_filtered[data_filtered['Price Range'].str.contains('₹', na=False)]
    print("Cleaned data shape (rows with ₹):", data_cleaned.shape)
else:
    print("The 'Price Range' column is not present in the dataset.")
    data_cleaned = data_filtered

# Reset the index
data_cleaned.reset_index(drop=True, inplace=True)

# # Save the cleaned dataset
output_path = 'cleaned_price_with_rupee.csv'
data_cleaned.to_csv(output_path, index=False)

print(f"Cleaned dataset saved to: {output_path}")

Initial data shape: (186, 5)
Cleaned data shape (rows with ₹): (126, 5)
Cleaned dataset saved to: cleaned_price_with_rupee.csv